### ISSUE TITLE
Issues on installation and setting new project

### ISSUE THREAD

**Issue by shacharsol** [banderson/generator-flux-react#49]
There are missing dependencies when i try to run the new generated server:

/Users/XX/projects/web/flux-test/node_modules/gulp-eslint/index.js:3
const BufferStreams = require('bufferstreams');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/XX/projects/web/flux-test/gulp/tasks/lint.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! objective-user-award@0.1.0 dev: `gulp --type dev`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the objective-user-award@0.1.0 dev script.
npm ERR! This is most likely a problem with the objective-user-award package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --type dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls objective-user-award
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 16.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! cwd /Users/XX/projects/web/flux-test
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/XX/projects/web/flux-test/npm-debug.log
npm ERR! not ok code 0

**Comment by shacharsol** [comment]
also on installation:
npm http 304 https://registry.npmjs.org/regenerator-runtime
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.3.2 wants react@^15.3.2
npm ERR! peerinvalid Peer flux@3.1.0 wants react@^15.0.2
npm ERR! peerinvalid Peer react-bootstrap@0.30.6 wants react@>=0.14.0

npm ERR! System Darwin 16.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "install" "react-bootstrap" "--save"
npm ERR! cwd /Users/shacharsolomon/projects/web/flux-test
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/shacharsolomon/projects/web/flux-test/npm-debug.log
npm ERR! not ok code 0
